before:
  hooks:
    - go mod download

builds:
  - main: ./awssh/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      -X github.com/youyo/awssh/awssh/cmd.Version={{ .Version }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - id: github release
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    github:
      owner: youyo
      name: homebrew-tap
    folder: Formula
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    description: "CLI tool to login ec2 instance"
    homepage: "https://github.com/youyo/awssh"
    install: |
      bin.install "awssh"
      output = `#{bin}/awssh --completion-zsh`
      (zsh_completion/"_awssh").write output
    test: |
      system "#{bin}/awssh --version"
